const products = [
  {
    title: "Premium Polo T-Shirt",
    description: "Classic polo t-shirt with premium cotton fabric.",
    category: "T-Shirts",
    price: 1299,
    originalPrice: 1699,
    discountPercentage: 24,
    gender: "Male",
    material: "Cotton",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=25"],
    sizes: [
      { size: "M", stock: 12 },
      { size: "L", stock: 10 },
      { size: "XL", stock: 8 },
    ],
  },

  {
    title: "Women's Relaxed Tee",
    description: "Soft cotton tee designed for all-day comfort.",
    category: "T-Shirts",
    price: 899,
    originalPrice: 1199,
    discountPercentage: 25,
    gender: "Female",
    material: "Cotton",
    fit: "Relaxed",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=26"],
    sizes: [
      { size: "S", stock: 12 },
      { size: "M", stock: 15 },
      { size: "L", stock: 10 },
    ],
  },

  {
    title: "Oversized Anime Tee",
    description: "Streetwear oversized t-shirt with anime inspired print.",
    category: "T-Shirts",
    price: 1099,
    originalPrice: 1499,
    discountPercentage: 27,
    gender: "Unisex",
    material: "Cotton",
    fit: "Oversized",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=27"],
    sizes: [
      { size: "M", stock: 15 },
      { size: "L", stock: 14 },
      { size: "XL", stock: 12 },
    ],
  },

  {
    title: "Business Casual Shirt",
    description: "Modern shirt suitable for office and casual wear.",
    category: "Shirts",
    price: 1799,
    originalPrice: 2399,
    discountPercentage: 25,
    gender: "Male",
    material: "Cotton",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=28"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 12 },
      { size: "XL", stock: 7 },
    ],
  },

  {
    title: "Women's Linen Shirt",
    description: "Lightweight linen shirt with elegant styling.",
    category: "Shirts",
    price: 1699,
    originalPrice: 2299,
    discountPercentage: 26,
    gender: "Female",
    material: "Linen",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=29"],
    sizes: [
      { size: "S", stock: 10 },
      { size: "M", stock: 12 },
      { size: "L", stock: 8 },
    ],
  },

  {
    title: "Heavyweight Street Hoodie",
    description: "Premium heavyweight hoodie built for streetwear lovers.",
    category: "Hoodies",
    price: 2499,
    originalPrice: 3299,
    discountPercentage: 24,
    gender: "Unisex",
    material: "Cotton",
    fit: "Oversized",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=30"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 12 },
      { size: "XL", stock: 10 },
    ],
  },

  {
    title: "Women's Cropped Hoodie",
    description: "Trendy cropped hoodie with ultra-soft fleece lining.",
    category: "Hoodies",
    price: 1999,
    originalPrice: 2699,
    discountPercentage: 26,
    gender: "Female",
    material: "Fleece",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=31"],
    sizes: [
      { size: "S", stock: 10 },
      { size: "M", stock: 12 },
      { size: "L", stock: 8 },
    ],
  },

  {
    title: "Black Slim Fit Jeans",
    description: "Stretchable slim fit black jeans for everyday styling.",
    category: "Jeans",
    price: 1999,
    originalPrice: 2599,
    discountPercentage: 23,
    gender: "Male",
    material: "Denim",
    fit: "Slim",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=32"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 8 },
      { size: "XL", stock: 6 },
    ],
  },

  {
    title: "Women's Straight Fit Jeans",
    description: "Classic straight fit denim with premium finish.",
    category: "Jeans",
    price: 1899,
    originalPrice: 2499,
    discountPercentage: 24,
    gender: "Female",
    material: "Denim",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=33"],
    sizes: [
      { size: "S", stock: 12 },
      { size: "M", stock: 10 },
      { size: "L", stock: 8 },
    ],
  },

  {
    title: "Utility Cargo Pants",
    description: "Functional cargo pants featuring multiple utility pockets.",
    category: "Cargo Pants",
    price: 1999,
    originalPrice: 2699,
    discountPercentage: 26,
    gender: "Male",
    material: "Cotton",
    fit: "Relaxed",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=34"],
    sizes: [
      { size: "M", stock: 12 },
      { size: "L", stock: 10 },
      { size: "XL", stock: 8 },
    ],
  },
  {
    title: "Premium Polo T-Shirt",
    description: "Classic polo t-shirt with premium cotton fabric.",
    category: "T-Shirts",
    price: 1299,
    originalPrice: 1699,
    discountPercentage: 24,
    gender: "Male",
    material: "Cotton",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=25"],
    sizes: [
      { size: "M", stock: 12 },
      { size: "L", stock: 10 },
      { size: "XL", stock: 8 },
    ],
  },

  {
    title: "Women's Relaxed Tee",
    description: "Soft cotton tee designed for all-day comfort.",
    category: "T-Shirts",
    price: 899,
    originalPrice: 1199,
    discountPercentage: 25,
    gender: "Female",
    material: "Cotton",
    fit: "Relaxed",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=26"],
    sizes: [
      { size: "S", stock: 12 },
      { size: "M", stock: 15 },
      { size: "L", stock: 10 },
    ],
  },

  {
    title: "Oversized Anime Tee",
    description: "Streetwear oversized t-shirt with anime inspired print.",
    category: "T-Shirts",
    price: 1099,
    originalPrice: 1499,
    discountPercentage: 27,
    gender: "Unisex",
    material: "Cotton",
    fit: "Oversized",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=27"],
    sizes: [
      { size: "M", stock: 15 },
      { size: "L", stock: 14 },
      { size: "XL", stock: 12 },
    ],
  },

  {
    title: "Business Casual Shirt",
    description: "Modern shirt suitable for office and casual wear.",
    category: "Shirts",
    price: 1799,
    originalPrice: 2399,
    discountPercentage: 25,
    gender: "Male",
    material: "Cotton",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=28"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 12 },
      { size: "XL", stock: 7 },
    ],
  },

  {
    title: "Women's Linen Shirt",
    description: "Lightweight linen shirt with elegant styling.",
    category: "Shirts",
    price: 1699,
    originalPrice: 2299,
    discountPercentage: 26,
    gender: "Female",
    material: "Linen",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=29"],
    sizes: [
      { size: "S", stock: 10 },
      { size: "M", stock: 12 },
      { size: "L", stock: 8 },
    ],
  },

  {
    title: "Heavyweight Street Hoodie",
    description: "Premium heavyweight hoodie built for streetwear lovers.",
    category: "Hoodies",
    price: 2499,
    originalPrice: 3299,
    discountPercentage: 24,
    gender: "Unisex",
    material: "Cotton",
    fit: "Oversized",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=30"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 12 },
      { size: "XL", stock: 10 },
    ],
  },

  {
    title: "Women's Cropped Hoodie",
    description: "Trendy cropped hoodie with ultra-soft fleece lining.",
    category: "Hoodies",
    price: 1999,
    originalPrice: 2699,
    discountPercentage: 26,
    gender: "Female",
    material: "Fleece",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=31"],
    sizes: [
      { size: "S", stock: 10 },
      { size: "M", stock: 12 },
      { size: "L", stock: 8 },
    ],
  },

  {
    title: "Black Slim Fit Jeans",
    description: "Stretchable slim fit black jeans for everyday styling.",
    category: "Jeans",
    price: 1999,
    originalPrice: 2599,
    discountPercentage: 23,
    gender: "Male",
    material: "Denim",
    fit: "Slim",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=32"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 8 },
      { size: "XL", stock: 6 },
    ],
  },

  {
    title: "Women's Straight Fit Jeans",
    description: "Classic straight fit denim with premium finish.",
    category: "Jeans",
    price: 1899,
    originalPrice: 2499,
    discountPercentage: 24,
    gender: "Female",
    material: "Denim",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=33"],
    sizes: [
      { size: "S", stock: 12 },
      { size: "M", stock: 10 },
      { size: "L", stock: 8 },
    ],
  },

  {
    title: "Utility Cargo Pants",
    description: "Functional cargo pants featuring multiple utility pockets.",
    category: "Cargo Pants",
    price: 1999,
    originalPrice: 2699,
    discountPercentage: 26,
    gender: "Male",
    material: "Cotton",
    fit: "Relaxed",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=34"],
    sizes: [
      { size: "M", stock: 12 },
      { size: "L", stock: 10 },
      { size: "XL", stock: 8 },
    ],
  },
  {
    title: "Streetwear Baggy Cargo Pants",
    description: "Baggy cargo pants inspired by modern street fashion.",
    category: "Cargo Pants",
    price: 2299,
    originalPrice: 3099,
    discountPercentage: 26,
    gender: "Unisex",
    material: "Cotton",
    fit: "Oversized",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=35"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 12 },
      { size: "XL", stock: 10 },
    ],
  },

  {
    title: "Women's Relaxed Cargo Pants",
    description: "Comfortable relaxed fit cargo pants with utility pockets.",
    category: "Cargo Pants",
    price: 1899,
    originalPrice: 2499,
    discountPercentage: 24,
    gender: "Female",
    material: "Cotton",
    fit: "Relaxed",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=36"],
    sizes: [
      { size: "S", stock: 10 },
      { size: "M", stock: 12 },
      { size: "L", stock: 8 },
    ],
  },

  {
    title: "Classic Black Joggers",
    description: "Minimal joggers designed for comfort and daily wear.",
    category: "Joggers",
    price: 1499,
    originalPrice: 1999,
    discountPercentage: 25,
    gender: "Unisex",
    material: "Cotton",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=37"],
    sizes: [
      { size: "M", stock: 12 },
      { size: "L", stock: 10 },
      { size: "XL", stock: 8 },
    ],
  },

  {
    title: "Premium Training Joggers",
    description: "Performance joggers built for gym and active lifestyles.",
    category: "Joggers",
    price: 1699,
    originalPrice: 2299,
    discountPercentage: 26,
    gender: "Male",
    material: "Polyester",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=38"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 12 },
      { size: "XL", stock: 7 },
    ],
  },

  {
    title: "Women's Fleece Joggers",
    description: "Ultra-soft fleece joggers for cozy everyday comfort.",
    category: "Joggers",
    price: 1599,
    originalPrice: 2199,
    discountPercentage: 27,
    gender: "Female",
    material: "Fleece",
    fit: "Relaxed",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=39"],
    sizes: [
      { size: "S", stock: 10 },
      { size: "M", stock: 12 },
      { size: "L", stock: 8 },
    ],
  },

  {
    title: "Summer Beach Shorts",
    description: "Lightweight shorts perfect for summer vacations.",
    category: "Shorts",
    price: 999,
    originalPrice: 1399,
    discountPercentage: 29,
    gender: "Male",
    material: "Cotton",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=40"],
    sizes: [
      { size: "M", stock: 12 },
      { size: "L", stock: 10 },
      { size: "XL", stock: 8 },
    ],
  },

  {
    title: "Athletic Running Shorts",
    description: "Breathable shorts designed for running and training.",
    category: "Shorts",
    price: 1199,
    originalPrice: 1599,
    discountPercentage: 25,
    gender: "Unisex",
    material: "Polyester",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=41"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 12 },
      { size: "XL", stock: 8 },
    ],
  },

  {
    title: "Women's Casual Shorts",
    description: "Comfortable casual shorts for daily summer wear.",
    category: "Shorts",
    price: 1099,
    originalPrice: 1499,
    discountPercentage: 27,
    gender: "Female",
    material: "Cotton",
    fit: "Relaxed",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=42"],
    sizes: [
      { size: "S", stock: 12 },
      { size: "M", stock: 10 },
      { size: "L", stock: 8 },
    ],
  },

  {
    title: "Classic Denim Jacket",
    description: "Timeless denim jacket suitable for every wardrobe.",
    category: "Jackets",
    price: 2499,
    originalPrice: 3299,
    discountPercentage: 24,
    gender: "Unisex",
    material: "Denim",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=43"],
    sizes: [
      { size: "M", stock: 8 },
      { size: "L", stock: 10 },
      { size: "XL", stock: 6 },
    ],
  },

  {
    title: "Premium Bomber Jacket",
    description: "Modern bomber jacket with lightweight premium construction.",
    category: "Jackets",
    price: 2999,
    originalPrice: 3999,
    discountPercentage: 25,
    gender: "Unisex",
    material: "Polyester",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=44"],
    sizes: [
      { size: "M", stock: 8 },
      { size: "L", stock: 10 },
      { size: "XL", stock: 7 },
    ],
  },
  {
    title: "Women's Denim Jacket",
    description: "Stylish cropped denim jacket perfect for layering.",
    category: "Jackets",
    price: 2699,
    originalPrice: 3499,
    discountPercentage: 23,
    gender: "Female",
    material: "Denim",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=45"],
    sizes: [
      { size: "S", stock: 8 },
      { size: "M", stock: 10 },
      { size: "L", stock: 6 },
    ],
  },

  {
    title: "Luxury Oversized Hoodie",
    description: "Heavyweight premium hoodie with ultra-soft brushed interior.",
    category: "Hoodies",
    price: 3499,
    originalPrice: 4499,
    discountPercentage: 22,
    gender: "Unisex",
    material: "Fleece",
    fit: "Oversized",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=46"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 12 },
      { size: "XL", stock: 10 },
      { size: "XXL", stock: 6 },
    ],
  },

  {
    title: "Street Cargo Pro",
    description: "Premium oversized cargo pants with utility-inspired design.",
    category: "Cargo Pants",
    price: 2599,
    originalPrice: 3499,
    discountPercentage: 26,
    gender: "Unisex",
    material: "Cotton",
    fit: "Oversized",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=47"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 12 },
      { size: "XL", stock: 8 },
    ],
  },

  {
    title: "Signature Graphic Tee",
    description:
      "Best-selling inspired graphic tee with premium print quality.",
    category: "T-Shirts",
    price: 1199,
    originalPrice: 1599,
    discountPercentage: 25,
    gender: "Unisex",
    material: "Cotton",
    fit: "Oversized",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=48"],
    sizes: [
      { size: "S", stock: 15 },
      { size: "M", stock: 18 },
      { size: "L", stock: 15 },
      { size: "XL", stock: 12 },
    ],
  },

  {
    title: "Premium Straight Fit Jeans",
    description:
      "High-quality denim jeans with a clean straight-leg silhouette.",
    category: "Jeans",
    price: 2499,
    originalPrice: 3299,
    discountPercentage: 24,
    gender: "Male",
    material: "Denim",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=49"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 12 },
      { size: "XL", stock: 8 },
    ],
  },

  {
    title: "Limited Edition Hoodie",
    description:
      "Exclusive hoodie currently out of stock for testing purposes.",
    category: "Hoodies",
    price: 2799,
    originalPrice: 3599,
    discountPercentage: 22,
    gender: "Unisex",
    material: "Cotton",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=50"],
    sizes: [
      { size: "M", stock: 0 },
      { size: "L", stock: 0 },
      { size: "XL", stock: 0 },
    ],
  },
  {
    title: "Classic Denim Jacket",
    description: "Timeless denim jacket with versatile styling.",
    category: "Jackets",
    price: 2499,
    originalPrice: 3299,
    discountPercentage: 24,
    gender: "Unisex",
    material: "Denim",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=23"],
    sizes: [
      { size: "M", stock: 8 },
      { size: "L", stock: 10 },
      { size: "XL", stock: 6 },
    ],
  },
  {
    title: "Bomber Jacket",
    description: "Modern bomber jacket with lightweight comfort.",
    category: "Jackets",
    price: 2799,
    originalPrice: 3699,
    discountPercentage: 24,
    gender: "Unisex",
    material: "Polyester",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=24"],
    sizes: [
      { size: "M", stock: 8 },
      { size: "L", stock: 9 },
      { size: "XL", stock: 7 },
    ],
  },
  {
    title: "Summer Cotton Shorts",
    description: "Lightweight cotton shorts perfect for warm days.",
    category: "Shorts",
    price: 999,
    originalPrice: 1399,
    discountPercentage: 29,
    gender: "Male",
    material: "Cotton",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=21"],
    sizes: [
      { size: "M", stock: 12 },
      { size: "L", stock: 10 },
      { size: "XL", stock: 8 },
    ],
  },
  {
    title: "Athletic Training Shorts",
    description: "Breathable performance shorts for workouts and sports.",
    category: "Shorts",
    price: 1199,
    originalPrice: 1599,
    discountPercentage: 25,
    gender: "Unisex",
    material: "Polyester",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=22"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 12 },
      { size: "XL", stock: 8 },
    ],
  },
  {
    title: "Essential Black Joggers",
    description: "Comfortable everyday joggers with tapered fit.",
    category: "Joggers",
    price: 1499,
    originalPrice: 1999,
    discountPercentage: 25,
    gender: "Unisex",
    material: "Cotton",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=19"],
    sizes: [
      { size: "M", stock: 12 },
      { size: "L", stock: 10 },
      { size: "XL", stock: 7 },
    ],
  },
  {
    title: "Premium Fleece Joggers",
    description: "Warm fleece joggers designed for all-day comfort.",
    category: "Joggers",
    price: 1699,
    originalPrice: 2299,
    discountPercentage: 26,
    gender: "Unisex",
    material: "Fleece",
    fit: "Relaxed",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=20"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 12 },
      { size: "XL", stock: 8 },
    ],
  },
  {
    title: "Urban Cargo Pants",
    description: "Utility inspired cargo pants with multiple pockets.",
    category: "Cargo Pants",
    price: 1799,
    originalPrice: 2399,
    discountPercentage: 25,
    gender: "Male",
    material: "Cotton",
    fit: "Relaxed",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=16"],
    sizes: [
      { size: "M", stock: 12 },
      { size: "L", stock: 10 },
      { size: "XL", stock: 8 },
    ],
  },
  {
    title: "Tactical Cargo Pants",
    description: "Durable cargo pants built for comfort and functionality.",
    category: "Cargo Pants",
    price: 1999,
    originalPrice: 2699,
    discountPercentage: 26,
    gender: "Male",
    material: "Cotton",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=17"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 12 },
      { size: "XL", stock: 7 },
    ],
  },
  {
    title: "Oversized Street Cargo",
    description: "Loose fit cargo pants for a modern streetwear look.",
    category: "Cargo Pants",
    price: 2299,
    originalPrice: 3099,
    discountPercentage: 26,
    gender: "Unisex",
    material: "Cotton",
    fit: "Oversized",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=18"],
    sizes: [
      { size: "M", stock: 9 },
      { size: "L", stock: 11 },
      { size: "XL", stock: 8 },
    ],
  },
  {
    title: "Slim Fit Blue Jeans",
    description: "Classic slim fit denim jeans for everyday wear.",
    category: "Jeans",
    price: 1899,
    originalPrice: 2499,
    discountPercentage: 24,
    gender: "Male",
    material: "Denim",
    fit: "Slim",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=13"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 8 },
      { size: "XL", stock: 6 },
    ],
  },
  {
    title: "Relaxed Fit Denim Jeans",
    description: "Comfortable relaxed fit jeans with premium wash.",
    category: "Jeans",
    price: 1999,
    originalPrice: 2699,
    discountPercentage: 26,
    gender: "Male",
    material: "Denim",
    fit: "Relaxed",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=14"],
    sizes: [
      { size: "M", stock: 12 },
      { size: "L", stock: 10 },
      { size: "XL", stock: 7 },
    ],
  },
  {
    title: "Vintage Washed Jeans",
    description: "Streetwear inspired washed denim with modern styling.",
    category: "Jeans",
    price: 2199,
    originalPrice: 2999,
    discountPercentage: 27,
    gender: "Unisex",
    material: "Denim",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=15"],
    sizes: [
      { size: "M", stock: 9 },
      { size: "L", stock: 11 },
      { size: "XL", stock: 8 },
    ],
  },
  {
    title: "Urban Oversized Graphic Tee",
    description:
      "Premium cotton oversized t-shirt with minimal streetwear graphics.",
    category: "T-Shirts",
    price: 899,
    originalPrice: 1299,
    discountPercentage: 31,
    gender: "Unisex",
    material: "Cotton",
    fit: "Oversized",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=1"],
    sizes: [
      { size: "S", stock: 10 },
      { size: "M", stock: 15 },
      { size: "L", stock: 12 },
      { size: "XL", stock: 8 },
    ],
  },
  {
    title: "Classic White T-Shirt",
    description:
      "Everyday regular fit t-shirt made from soft breathable cotton.",
    category: "T-Shirts",
    price: 699,
    originalPrice: 999,
    discountPercentage: 30,
    gender: "Unisex",
    material: "Cotton",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=2"],
    sizes: [
      { size: "S", stock: 8 },
      { size: "M", stock: 14 },
      { size: "L", stock: 10 },
    ],
  },
  {
    title: "Vintage Washed Tee",
    description:
      "Relaxed fit washed t-shirt inspired by vintage streetwear trends.",
    category: "T-Shirts",
    price: 999,
    originalPrice: 1399,
    discountPercentage: 29,
    gender: "Unisex",
    material: "Cotton",
    fit: "Relaxed",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=3"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 12 },
      { size: "XL", stock: 6 },
    ],
  },
  {
    title: "Essential Black Tee",
    description: "Minimal black t-shirt designed for comfort and daily wear.",
    category: "T-Shirts",
    price: 799,
    originalPrice: 1099,
    discountPercentage: 27,
    gender: "Male",
    material: "Cotton",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=4"],
    sizes: [
      { size: "S", stock: 9 },
      { size: "M", stock: 12 },
      { size: "L", stock: 8 },
    ],
  },
  {
    title: "Oxford Casual Shirt",
    description: "Premium oxford shirt suitable for office and casual outings.",
    category: "Shirts",
    price: 1499,
    originalPrice: 1999,
    discountPercentage: 25,
    gender: "Male",
    material: "Cotton",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=5"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 12 },
      { size: "XL", stock: 7 },
    ],
  },
  {
    title: "Slim Fit Formal Shirt",
    description: "Smart slim fit shirt crafted for a clean and modern look.",
    category: "Shirts",
    price: 1599,
    originalPrice: 2199,
    discountPercentage: 27,
    gender: "Male",
    material: "Cotton",
    fit: "Slim",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=6"],
    sizes: [
      { size: "M", stock: 8 },
      { size: "L", stock: 10 },
      { size: "XL", stock: 5 },
    ],
  },
  {
    title: "Checked Casual Shirt",
    description:
      "Classic checked shirt with relaxed styling for everyday comfort.",
    category: "Shirts",
    price: 1399,
    originalPrice: 1899,
    discountPercentage: 26,
    gender: "Male",
    material: "Cotton",
    fit: "Relaxed",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=7"],
    sizes: [
      { size: "S", stock: 7 },
      { size: "M", stock: 11 },
      { size: "L", stock: 9 },
    ],
  },
  {
    title: "Linen Summer Shirt",
    description: "Lightweight linen shirt designed for warm weather comfort.",
    category: "Shirts",
    price: 1699,
    originalPrice: 2299,
    discountPercentage: 26,
    gender: "Male",
    material: "Linen",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=8"],
    sizes: [
      { size: "M", stock: 9 },
      { size: "L", stock: 12 },
      { size: "XL", stock: 6 },
    ],
  },
  {
    title: "Classic Pullover Hoodie",
    description: "Soft fleece hoodie built for comfort and everyday layering.",
    category: "Hoodies",
    price: 1899,
    originalPrice: 2499,
    discountPercentage: 24,
    gender: "Unisex",
    material: "Fleece",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=9"],
    sizes: [
      { size: "M", stock: 12 },
      { size: "L", stock: 14 },
      { size: "XL", stock: 8 },
    ],
  },
  {
    title: "Oversized Street Hoodie",
    description:
      "Streetwear inspired oversized hoodie with heavyweight fabric.",
    category: "Hoodies",
    price: 2199,
    originalPrice: 2999,
    discountPercentage: 27,
    gender: "Unisex",
    material: "Cotton",
    fit: "Oversized",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=10"],
    sizes: [
      { size: "M", stock: 10 },
      { size: "L", stock: 12 },
      { size: "XL", stock: 10 },
    ],
  },
  {
    title: "Zip-Up Hoodie",
    description: "Versatile zip-up hoodie perfect for daily wear and layering.",
    category: "Hoodies",
    price: 1999,
    originalPrice: 2699,
    discountPercentage: 26,
    gender: "Unisex",
    material: "Fleece",
    fit: "Regular",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=11"],
    sizes: [
      { size: "S", stock: 8 },
      { size: "M", stock: 12 },
      { size: "L", stock: 10 },
    ],
  },
  {
    title: "Vintage Washed Hoodie",
    description: "Relaxed fit washed hoodie with a premium vintage aesthetic.",
    category: "Hoodies",
    price: 2299,
    originalPrice: 3099,
    discountPercentage: 26,
    gender: "Unisex",
    material: "Cotton",
    fit: "Relaxed",
    featured: false,
    bestSeller: false,
    newArrival: false,
    images: ["https://picsum.photos/600/800?random=12"],
    sizes: [
      { size: "M", stock: 8 },
      { size: "L", stock: 10 },
      { size: "XL", stock: 8 },
    ],
  },
];

module.exports = products;
